export const FETCH_USER = "FETCH_USER"

// Product's types
export const FETCH_PRODUCT_ITEM = "FETCH_PRODUCT_ITEM"
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const FETCH_RESTOCK_PRODUCTS = "FETCH_RESTOCK_PRODUCTS"
export const LOADING_PRODUCT = "LOADING_PRODUCT"
export const FETCH_PRODUCT_CATEGORIES = "FETCH_PRODUCT_CATEGORIES"
export const ERROR_PRODUCT = "ERROR_PRODUCT"

// RajaOngkir's types
export const LOADING_RAJAONGKIR = "LOADING_RAJAONGKIR"
export const FETCH_PROVINCES = "FETCH_PROVINCES"
export const FETCH_CITIES = "FETCH_CITIES"
export const FETCH_SUBDISTRICTS = "FETCH_SUBDISTRICTS"
export const FETCH_COURIERS = "FETCH_COURIERS"

// Auth's types
export const LOADING_USER = "LOADING_USER"
export const AUTH_USER = "AUTH_USER"
export const UNAUTH_USER = "UNAUTH_USER"

// Other types
export const SET_CART_DRAWER_FROM_STORE = "SET_CART_DRAWER_FROM_STORE"
export const LOADING_OTHER = "LOADING_OTHER"
export const FETCH_ORDER_CODE_LIST = "FETCH_ORDER_CODE_LIST"
export const FETCH_BANK_ACCOUNTS = "FETCH_BANK_ACCOUNTS"
export const FETCH_CUSTOMER_SERVICES = "FETCH_CUSTOMER_SERVICES"
