export const FETCH_USER = "FETCH_USER"

// Product's types
export const FETCH_PRODUCT_ITEM = "FETCH_PRODUCT_ITEM"
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const LOADING_PRODUCT = "LOADING_PRODUCT"
export const ERROR_PRODUCT = "ERROR_PRODUCT"

// RajaOngkir's types
export const FETCH_PROVINCES = "FETCH_PROVINCES"
export const FETCH_CITIES = "FETCH_CITIES"
export const LOADING_RAJAONGKIR = "LOADING_RAJAONGKIR"
